spring.application.name=springmvc

#hello.springmvc 패키지와 그 하위 로그 레벨 설정
#trace debug info warn error
#일반적으로 로컬-trace, 개발서버-debug, 운영서버-info

#전체 로그 레벨 설정(기본 info)
#logging.level.root=debug

logging.level.hello.springmvc=debug