spring.application.name=exception

#spring.messages.basename=messages

# ?? whitelabel ????? ??. ? ?? ??? ?????? ???
server.error.whitelabel.enabled=false

# exception ?? ??( true , false )
#server.error.include-exception=true

# message ?? ??
server.error.include-message=always

# trace ?? ??
#server.error.include-stacktrace=on_param

# errors ?? ??
#server.error.include-binding-errors=on_param




